### PR TITLE
Fix usage of deprecated behaviours and methods in SCSS PHP filter

### LINKED ISSUE #11: Custom functions in ScssphpFilter are not exposing the full upstream API
`ScssphpFilter::registerFunction` only exposes arguments for the name and the callable.
But the ScssPhp API supports a third argument to configure the Sass signature (or signatures) of the function, and this parameter is not exposed in any way in Assetic.
Currently, this parameter is optional, with a different behavior when you don't have it or you have it. and the behavior without knowing the signature is not spec-compliant (as the compiler is expected to validate the signature). As such, the plan is to make that argument mandatory in 2.0 of scssphp. It would be great if Assetic could allow using this argument.

Note that we currently plan a refactoring in scssphp which will impact the implementation of custom functions, for which we plan to add a new (optional) argument in `registerFunction` to opt-in for the new behavior (which also won't allow omitting the signature). Once that argument appears, it might make sense to support it too (forcing the value to opt-in or opt-out in ScssphpFilter itself would defeat the purpose of the per-function opt-in)

### PR DESCRIPTION
**Pull request by bennothommo**
- Adds additional argument for registerFunction method to define argument declarations (fixes #11)
- Uses compileString() method for compilation as opposed to deprecated compile() method
- Uses addVariables() method for defining variables as opposed to deprecated setVariables() method
- Parses variables provided in the setVariables() filter method and converts to Scss values, avoiding the deprecated behavior of allowing raw variables

This should also hopefully fix the PHPUnit tests.

### CODE REVIEW

File: src/Assetic/Filter/ScssphpFilter.php [hunk 1]
```diff
@@ -99,9 +104,12 @@ public function addImportPath($path)
         $this->importPaths[] = $path;
     }
 
-    public function registerFunction($name, $callable)
+    public function registerFunction($name, $callable, $argumentDeclaration = null)
```
Comment (stof) [inline src/Assetic/Filter/ScssphpFilter.php]: you could typehint the new argument as `array`

Comment (bennothommo) [reply src/Assetic/Filter/ScssphpFilter.php]: Thanks @stof
